export const DAYZ_ITEMS = [
  // ─── WEAPONS ───────────────────────────────────────
  { name:'AS VAL', category:'Weapons', tags:['as val','asval','val'] },
  { name:'AUR A1', category:'Weapons', tags:['aur a1','aura1','aur'] },
  { name:'Bizon', category:'Weapons', tags:['bizon','pp19'] },
  { name:'BK-12', category:'Weapons', tags:['bk12','bk-12'] },
  { name:'BK-133', category:'Weapons', tags:['bk133','bk-133'] },
  { name:'BK-18', category:'Weapons', tags:['bk18','bk-18'] },
  { name:'BK-43', category:'Weapons', tags:['bk43','bk-43'] },
  { name:'Blaze', category:'Weapons', tags:['blaze'] },
  { name:'CR-527', category:'Weapons', tags:['cr527','cr-527'] },
  { name:'CR-550 Savanna', category:'Weapons', tags:['cr550','savanna','cr-550'] },
  { name:'CR-61 Skorpion', category:'Weapons', tags:['cr61','skorpion','cr-61'] },
  { name:'CR-75', category:'Weapons', tags:['cr75','cr-75'] },
  { name:'Deagle', category:'Weapons', tags:['deagle','desert eagle'] },
  { name:'Derringer', category:'Weapons', tags:['derringer'] },
  { name:'DMR', category:'Weapons', tags:['dmr'] },
  { name:'Engraved Kolt 1911', category:'Weapons', tags:['engraved 1911','engraved kolt'] },
  { name:'FX-45', category:'Weapons', tags:['fx45','fx-45'] },
  { name:'IJ-70', category:'Weapons', tags:['ij70','ij-70'] },
  { name:'KA-M', category:'Weapons', tags:['kam','ka-m','akm'] },
  { name:'KAS-74U', category:'Weapons', tags:['kas74u','kas-74u','aks74u'] },
  { name:'KA-101', category:'Weapons', tags:['ka101','ka-101','ak101'] },
  { name:'KA-74', category:'Weapons', tags:['ka74','ka-74','ak74'] },
  { name:'Kolt 1911', category:'Weapons', tags:['kolt 1911','1911','kolt'] },
  { name:'LAR', category:'Weapons', tags:['lar','fal'] },
  { name:'LE-MAS', category:'Weapons', tags:['lemas','le-mas','le mas'] },
  { name:'Longhorn', category:'Weapons', tags:['longhorn'] },
  { name:'M16-A2', category:'Weapons', tags:['m16','m16a2','m16-a2'] },
  { name:'M4-A1', category:'Weapons', tags:['m4','m4a1','m4-a1'] },
  { name:'M79', category:'Weapons', tags:['m79'] },
  { name:'Revolver', category:'Weapons', tags:['revolver','magnum'] },
  { name:'MK II', category:'Weapons', tags:['mkii','mk ii','mk2'] },
  { name:'Mlock-91', category:'Weapons', tags:['mlock','mlock91','mlock-91','glock'] },
  { name:'Mosin 91/30', category:'Weapons', tags:['mosin','mosin 9130','mosin91'] },
  { name:'M70 Tundra', category:'Weapons', tags:['m70','tundra','m70 tundra'] },
  { name:'P1', category:'Weapons', tags:['p1 pistol','p1'] },
  { name:'Pioneer', category:'Weapons', tags:['pioneer'] },
  { name:'R12', category:'Weapons', tags:['r12'] },
  { name:'RAK-37', category:'Weapons', tags:['rak37','rak-37','rak'] },
  { name:'Repeater Carbine', category:'Weapons', tags:['repeater','repeater carbine'] },
  { name:'SG5-K', category:'Weapons', tags:['sg5k','sg5-k','mp5'] },
  { name:'Signal Pistol', category:'Weapons', tags:['signal pistol','flare gun'] },
  { name:'SK 59/66', category:'Weapons', tags:['sk5966','sk 59/66','sks'] },
  { name:'Sporter 22', category:'Weapons', tags:['sporter','sporter 22'] },
  { name:'SSG 82', category:'Weapons', tags:['ssg82','ssg 82'] },
  { name:'VS-89', category:'Weapons', tags:['vs89','sv98','vs-89','sv-98'] },
  { name:'USG-45', category:'Weapons', tags:['usg45','usg-45','ump'] },
  { name:'Vaiga', category:'Weapons', tags:['vaiga'] },
  { name:'Vikhr', category:'Weapons', tags:['vikhr'] },
  { name:'VSD', category:'Weapons', tags:['vsd'] },
  { name:'VSS', category:'Weapons', tags:['vss','vintorez'] },

  // ─── AMMO ──────────────────────────────────────────
  { name:'12 Gauge Buckshot', category:'Ammo', tags:['12 gauge buckshot','buckshot','12ga buckshot'] },
  { name:'12 Gauge Rubber Slugs', category:'Ammo', tags:['12 gauge rubber','rubber slugs','rubber slug'] },
  { name:'12 Gauge Slugs', category:'Ammo', tags:['12 gauge slugs','slugs','12ga slug'] },
  { name:'.22 Rounds', category:'Ammo', tags:['.22','22 rounds','22lr'] },
  { name:'.308 Rounds', category:'Ammo', tags:['.308','308 rounds','762x51'] },
  { name:'.357 Rounds', category:'Ammo', tags:['.357','357 rounds'] },
  { name:'.380 Rounds', category:'Ammo', tags:['.380','380 rounds'] },
  { name:'40mm Explosive Rounds', category:'Ammo', tags:['40mm explosive','40mm grenade'] },
  { name:'40mm Gas Rounds', category:'Ammo', tags:['40mm gas','pox grenade','40mm po-x'] },
  { name:'40mm Smoke Rounds', category:'Ammo', tags:['40mm smoke'] },
  { name:'.45 Rounds', category:'Ammo', tags:['.45','45 rounds','45acp'] },
  { name:'5.45x39 Rounds', category:'Ammo', tags:['545x39','5.45x39','5.45'] },
  { name:'5.56x45 Rounds', category:'Ammo', tags:['556x45','5.56x45','5.56'] },
  { name:'7.62x39 Rounds', category:'Ammo', tags:['762x39','7.62x39','7.62x39'] },
  { name:'7.62x54 Rounds', category:'Ammo', tags:['762x54','7.62x54'] },
  { name:'9mm Rounds', category:'Ammo', tags:['9mm','9x19','9mm rounds'] },
  { name:'9x39 Rounds', category:'Ammo', tags:['9x39'] },
  { name:'9x39 AP Rounds', category:'Ammo', tags:['9x39 ap','9x39 armour'] },
  { name:'Feathered Bolts', category:'Ammo', tags:['feathered bolts','bolts'] },
  { name:'Hunting Bolts', category:'Ammo', tags:['hunting bolts','bolt'] },
  { name:'Improvised Bolts', category:'Ammo', tags:['improvised bolts'] },
  { name:'Flare Cartridges', category:'Ammo', tags:['flare cartridge','flare cartridges'] },

  // ─── ATTACHMENTS ───────────────────────────────────
  { name:'ATOG 4x32 Scope', category:'Attachments', tags:['atog','atog 4x32','atog optic'] },
  { name:'ATOG 6x48 Scope', category:'Attachments', tags:['atog 6x48','atog x6'] },
  { name:'PU Scope', category:'Attachments', tags:['pu scope','pu'] },
  { name:'PSO-1 Scope', category:'Attachments', tags:['pso1','pso-1','pso 1'] },
  { name:'PSO-1-1 Scope', category:'Attachments', tags:['pso-1-1','pso 1 1'] },
  { name:'PSO-6 Scope', category:'Attachments', tags:['pso6','pso-6'] },
  { name:'NV-PVS4 Scope', category:'Attachments', tags:['pvs4','nv pvs4','night vision scope'] },
  { name:'Hunting Scope', category:'Attachments', tags:['hunting scope','hunting optic'] },
  { name:'Marksman Scope', category:'Attachments', tags:['marksman scope','marksman'] },
  { name:'Handgun Scope', category:'Attachments', tags:['handgun scope','pistol optic','pistol scope'] },
  { name:'P1-87-L Scope', category:'Attachments', tags:['p1 87','p1-87'] },
  { name:'1PN51 Scope', category:'Attachments', tags:['1pn51','1pn 51'] },
  { name:'Kobra Sights', category:'Attachments', tags:['kobra','kobra sights'] },
  { name:'Combat Sights', category:'Attachments', tags:['combat sights'] },
  { name:'Mini Sights', category:'Attachments', tags:['mini sights'] },
  { name:'RVN Sights', category:'Attachments', tags:['rvn sights','rvn'] },
  { name:'Baraka Sights', category:'Attachments', tags:['baraka sights','baraka'] },
  { name:'Sportpoint Sights', category:'Attachments', tags:['sportpoint','sportpoint sights'] },
  { name:'BUIS Sights', category:'Attachments', tags:['buis','backup iron sights'] },
  { name:'Carry Handle Sights', category:'Attachments', tags:['carry handle','carry handle sights'] },
  { name:'KA Suppressor', category:'Attachments', tags:['ka suppressor','normalized suppressor'] },
  { name:'M4 Suppressor', category:'Attachments', tags:['m4 suppressor','standardized suppressor'] },
  { name:'Pistol Suppressor', category:'Attachments', tags:['pistol suppressor'] },
  { name:'Improvised Suppressor', category:'Attachments', tags:['improvised suppressor'] },
  { name:'Universal Flashlight', category:'Attachments', tags:['universal flashlight'] },
  { name:'Pistol Flashlight', category:'Attachments', tags:['pistol flashlight'] },
  { name:'Ghillie Weapon Wrap', category:'Attachments', tags:['ghillie wrap','weapon wrap'] },
  { name:'KA Folding Buttstock', category:'Attachments', tags:['ka folding buttstock','ka lightweight buttstock'] },
  { name:'KA Wooden Buttstock', category:'Attachments', tags:['ka wooden buttstock'] },
  { name:'KA Polymer Buttstock', category:'Attachments', tags:['ka polymer buttstock'] },
  { name:'KA Wooden Handguard', category:'Attachments', tags:['ka wooden handguard'] },
  { name:'KA Polymer Handguard', category:'Attachments', tags:['ka polymer handguard'] },
  { name:'KA Rail Handguard', category:'Attachments', tags:['ka rail handguard'] },
  { name:'M4-A1 CQB Buttstock', category:'Attachments', tags:['m4 cqb buttstock','cqb buttstock'] },
  { name:'M4-A1 MP Buttstock', category:'Attachments', tags:['m4 mp buttstock'] },
  { name:'M4-A1 Telescopic Buttstock', category:'Attachments', tags:['m4 telescopic','telescopic buttstock'] },
  { name:'STANAG 30 Round Mag', category:'Attachments', tags:['stanag 30','stanag30','30rd standardized mag'] },
  { name:'STANAG 60 Round Mag', category:'Attachments', tags:['stanag 60','stanag60','60rd standardized mag'] },
  { name:'Coupled 60 Round Mag', category:'Attachments', tags:['coupled 60','coupled mag'] },
  { name:'KA-M 30 Round Mag', category:'Attachments', tags:['kam 30','30rd ka-m mag'] },
  { name:'KA-M 75 Round Drum Mag', category:'Attachments', tags:['kam 75','75rd ka-m drum'] },
  { name:'KA-74 30 Round Mag', category:'Attachments', tags:['ka74 30','30rd ka-74'] },
  { name:'KA-74 45 Round Mag', category:'Attachments', tags:['ka74 45','45rd ka-74'] },
  { name:'KA-101 30 Round Mag', category:'Attachments', tags:['ka101 30','30rd ka-101'] },
  { name:'KAS-74U Buttstock', category:'Attachments', tags:['kas74u buttstock','kas lightweight buttstock'] },

  // ─── MELEE ─────────────────────────────────────────
  { name:'Splitting Axe', category:'Tools', tags:['splitting axe','wood axe'] },
  { name:'Firefighter Axe', category:'Tools', tags:['firefighter axe','fire axe'] },
  { name:'Hatchet', category:'Tools', tags:['hatchet'] },
  { name:'Ice Axe', category:'Tools', tags:['ice axe'] },
  { name:'Pickaxe', category:'Tools', tags:['pickaxe'] },
  { name:'Shovel', category:'Tools', tags:['shovel'] },
  { name:'Field Shovel', category:'Tools', tags:['field shovel'] },
  { name:'Farming Hoe', category:'Tools', tags:['farming hoe','hoe'] },
  { name:'Sledgehammer', category:'Tools', tags:['sledgehammer'] },
  { name:'Hammer', category:'Tools', tags:['hammer'] },
  { name:'Hacksaw', category:'Tools', tags:['hacksaw'] },
  { name:'Hand Saw', category:'Tools', tags:['hand saw','handsaw'] },
  { name:'Crowbar', category:'Tools', tags:['crowbar'] },
  { name:'Pipe Wrench', category:'Tools', tags:['pipe wrench'] },
  { name:'Wrench', category:'Tools', tags:['wrench'] },
  { name:'Lug Wrench', category:'Tools', tags:['lug wrench','tire iron'] },
  { name:'Screwdriver', category:'Tools', tags:['screwdriver'] },
  { name:'Hunting Knife', category:'Tools', tags:['hunting knife'] },
  { name:'Combat Knife', category:'Tools', tags:['combat knife'] },
  { name:'Kitchen Knife', category:'Tools', tags:['kitchen knife'] },
  { name:'Steak Knife', category:'Tools', tags:['steak knife'] },
  { name:'Bone Knife', category:'Tools', tags:['bone knife'] },
  { name:'Stone Knife', category:'Tools', tags:['stone knife'] },
  { name:'Kukri', category:'Tools', tags:['kukri'] },
  { name:'Machete', category:'Tools', tags:['machete'] },
  { name:'Crude Machete', category:'Tools', tags:['crude machete'] },
  { name:'Oriental Machete', category:'Tools', tags:['oriental machete'] },
  { name:'Baseball Bat', category:'Tools', tags:['baseball bat'] },
  { name:'Nailed Baseball Bat', category:'Tools', tags:['nailed baseball bat','nailed bat'] },
  { name:'Barbed Baseball Bat', category:'Tools', tags:['barbed baseball bat','barbed bat'] },
  { name:'Brass Knuckles', category:'Tools', tags:['brass knuckles'] },
  { name:'Pitchfork', category:'Tools', tags:['pitchfork'] },
  { name:'Sickle', category:'Tools', tags:['sickle'] },
  { name:'Mace', category:'Tools', tags:['mace'] },
  { name:'Sword', category:'Tools', tags:['sword'] },
  { name:'Lead Pipe', category:'Tools', tags:['lead pipe','pipe'] },
  { name:'Meat Tenderizer', category:'Tools', tags:['meat tenderizer'] },

  // ─── EXPLOSIVES ────────────────────────────────────
  { name:'Claymore', category:'Weapons', tags:['claymore','claymore mine'] },
  { name:'Land Mine', category:'Weapons', tags:['land mine','landmine'] },
  { name:'Plastic Explosive', category:'Weapons', tags:['plastic explosive','c4'] },
  { name:'M67 Grenade', category:'Weapons', tags:['m67','frag grenade','6-m7'] },
  { name:'RDG-5 Grenade', category:'Weapons', tags:['rdg5','rdg-5','egd-5'] },
  { name:'Flashbang', category:'Weapons', tags:['flashbang','8-m4'] },
  { name:'M18 Smoke Grenade', category:'Weapons', tags:['m18 smoke','smoke grenade','m18'] },
  { name:'RDG-2 Smoke Grenade', category:'Weapons', tags:['rdg2 smoke','rdg-2'] },
  { name:'PO-X Vial', category:'Weapons', tags:['pox vial','po-x vial'] },
  { name:'Small Gas Canister', category:'Weapons', tags:['small gas canister'] },
  { name:'Medium Gas Canister', category:'Weapons', tags:['medium gas canister'] },
  { name:'Large Gas Canister', category:'Weapons', tags:['large gas canister'] },

  // ─── MEDICAL ───────────────────────────────────────
  { name:'Bandage', category:'Medical', tags:['bandage','bandages'] },
  { name:'Rag', category:'Medical', tags:['rag','rags'] },
  { name:'Morphine', category:'Medical', tags:['morphine'] },
  { name:'Epinephrine', category:'Medical', tags:['epinephrine','epi pen','epipen'] },
  { name:'Saline Bag', category:'Medical', tags:['saline','saline bag','iv bag'] },
  { name:'Blood Bag', category:'Medical', tags:['blood bag','blood'] },
  { name:'Tetracycline Pills', category:'Medical', tags:['tetracycline','tetracycline pills'] },
  { name:'Charcoal Tablets', category:'Medical', tags:['charcoal','charcoal tablets'] },
  { name:'Vitamins', category:'Medical', tags:['vitamins','vitamin'] },
  { name:'Iodine Tincture', category:'Medical', tags:['iodine','iodine tincture'] },
  { name:'Disinfectant Spray', category:'Medical', tags:['disinfectant','disinfectant spray'] },
  { name:'Surgical Kit', category:'Medical', tags:['surgical kit'] },
  { name:'Defibrillator', category:'Medical', tags:['defibrillator','defib'] },
  { name:'Tourniquet', category:'Medical', tags:['tourniquet'] },
  { name:'Splint', category:'Medical', tags:['splint'] },
  { name:'Medical Kit', category:'Medical', tags:['medical kit','medkit'] },
  { name:'Pain Killers', category:'Medical', tags:['pain killers','painkillers','pain killer'] },

  // ─── FOOD & WATER ───────────────────────────────────
  { name:'Canned Beans', category:'Food & Water', tags:['canned beans','beans'] },
  { name:'Canned Sardines', category:'Food & Water', tags:['canned sardines','sardines'] },
  { name:'Canned Spaghetti', category:'Food & Water', tags:['canned spaghetti','spaghetti'] },
  { name:'Canned Peaches', category:'Food & Water', tags:['canned peaches','peaches'] },
  { name:'Canned Peas', category:'Food & Water', tags:['canned peas','peas'] },
  { name:'Canned Tuna', category:'Food & Water', tags:['canned tuna','tuna'] },
  { name:'Powdered Milk', category:'Food & Water', tags:['powdered milk','milk powder'] },
  { name:'Rice', category:'Food & Water', tags:['rice'] },
  { name:'Pasta', category:'Food & Water', tags:['pasta'] },
  { name:'Flour', category:'Food & Water', tags:['flour'] },
  { name:'Sugar', category:'Food & Water', tags:['sugar'] },
  { name:'Salt', category:'Food & Water', tags:['salt'] },
  { name:'Apple', category:'Food & Water', tags:['apple','apples'] },
  { name:'Pear', category:'Food & Water', tags:['pear','pears'] },
  { name:'Plum', category:'Food & Water', tags:['plum','plums'] },
  { name:'Kiwi', category:'Food & Water', tags:['kiwi'] },
  { name:'Tomato', category:'Food & Water', tags:['tomato','tomatoes'] },
  { name:'Zucchini', category:'Food & Water', tags:['zucchini'] },
  { name:'Pumpkin', category:'Food & Water', tags:['pumpkin'] },
  { name:'Potato', category:'Food & Water', tags:['potato','potatoes'] },
  { name:'Water Bottle', category:'Food & Water', tags:['water bottle','bottle of water'] },
  { name:'Canteen', category:'Food & Water', tags:['canteen'] },
  { name:'Cooking Pot', category:'Food & Water', tags:['cooking pot','pot'] },
  { name:'Frying Pan', category:'Food & Water', tags:['frying pan','pan'] },

  // ─── BASE BUILDING ─────────────────────────────────
  { name:'Plank', category:'Base Building', tags:['plank','planks'] },
  { name:'Nails', category:'Base Building', tags:['nails','nail'] },
  { name:'Barbed Wire', category:'Base Building', tags:['barbed wire','barbedwire'] },
  { name:'Sandbag', category:'Base Building', tags:['sandbag','sandbags'] },
  { name:'Coil of Wire', category:'Base Building', tags:['coil of wire','wire coil','wire'] },
  { name:'Wooden Log', category:'Base Building', tags:['log','logs','wooden log'] },
  { name:'Short Stick', category:'Base Building', tags:['short stick','stick'] },
  { name:'Long Stick', category:'Base Building', tags:['long stick'] },
  { name:'Rope', category:'Base Building', tags:['rope'] },
  { name:'Metal Wire', category:'Base Building', tags:['metal wire'] },
  { name:'Fence Kit', category:'Base Building', tags:['fence kit'] },
  { name:'Watchtower Kit', category:'Base Building', tags:['watchtower kit','watchtower'] },
  { name:'Gate Kit', category:'Base Building', tags:['gate kit','gate'] },
  { name:'Tent', category:'Base Building', tags:['tent'] },
  { name:'Car Tent', category:'Base Building', tags:['car tent'] },
  { name:'Large Tent', category:'Base Building', tags:['large tent'] },
  { name:'Wooden Crate', category:'Base Building', tags:['wooden crate','crate'] },
  { name:'Barrel', category:'Base Building', tags:['barrel'] },
  { name:'Sea Chest', category:'Base Building', tags:['sea chest'] },
  { name:'Stone', category:'Base Building', tags:['stone','stones'] },

  // ─── VEHICLE PARTS ─────────────────────────────────
  { name:'Car Battery', category:'Vehicle Parts', tags:['car battery','battery'] },
  { name:'Spark Plug', category:'Vehicle Parts', tags:['spark plug','sparkplug'] },
  { name:'Headlight', category:'Vehicle Parts', tags:['headlight'] },
  { name:'Radiator', category:'Vehicle Parts', tags:['radiator'] },
  { name:'Engine Belt', category:'Vehicle Parts', tags:['engine belt','belt'] },
  { name:'Wheel', category:'Vehicle Parts', tags:['wheel','wheels','tire','tyre'] },
  { name:'Glow Plug', category:'Vehicle Parts', tags:['glow plug'] },
  { name:'Fuel Canister', category:'Vehicle Parts', tags:['fuel canister','jerry can','jerrycan'] },
]

export const ITEM_NAMES = DAYZ_ITEMS.map(i => i.name)

export function getItemCategory(name) {
  const item = DAYZ_ITEMS.find(i => i.name.toLowerCase() === name.toLowerCase())
  return item?.category || 'Other'
}

export function matchItem(rawText) {
  if (!rawText || rawText.length < 2) return null
  const text = rawText.toLowerCase().trim()

  // Exact name match
  const exact = DAYZ_ITEMS.find(i => i.name.toLowerCase() === text)
  if (exact) return { ...exact, confidence:'high', matched:exact.name }

  // Tag match
  const tagMatch = DAYZ_ITEMS.find(i => i.tags.some(tag => text.includes(tag) || tag.includes(text)))
  if (tagMatch) return { ...tagMatch, confidence:'medium', matched:tagMatch.name }

  // Partial name match
  const partial = DAYZ_ITEMS.find(i =>
    i.name.toLowerCase().includes(text) ||
    text.includes(i.name.toLowerCase().split(' ')[0])
  )
  if (partial) return { ...partial, confidence:'low', matched:partial.name }

  // Unknown - possible mod item
  return { name:rawText, category:'Unknown', confidence:'unknown', matched:rawText, possibleMod:true }
}